version: '3.8'

services:
  webserver:
    container_name: webserver
    build:
      context: .
    ports:
      - 82:80
    volumes:
      - ./CMS:/var/www/html
    networks:
      - default
    depends_on:
      - database
  database:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports: 
      - 3308:3306
    volumes:
      - persistent:/var/lib/mysql
      - ./sample_db.sql:/docker-entrypoint-initdb.d/sample_db.sql
    networks:
      - default

volumes:
  persistent:
    